### ISSUE TITLE
website appears to be broken

### ISSUE THREAD

**Issue by eugenio** [tom5760/ezproxy-db#2] opened 2016-10-11 03:21 UTC
The website gives this error:

```
Internal Server Error

The server has either erred or is incapable of performing the requested operation.

Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~ezproxy-db-hrd/3.395615253170389509/ezproxy_db.py", line 55, in get
    self.render_response('index.html', context)
  File "/base/data/home/apps/s~ezproxy-db-hrd/3.395615253170389509/ezproxy_db.py", line 22, in render_response
    self.response.write(self.jinja2.render_template(template, **context))
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2_extras/jinja2.py", line 158, in render_template
    return self.environment.get_template(_filename).render(**context)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/jinja2-2.6/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "templates/index.html", line 1, in top-level template code
    {% extends "main.html" %}
  File "templates/main.html", line 17, in top-level template code
    {% block body %}
  File "templates/index.html", line 64, in block "body"
    <h3>Proxies <small>{{ proxies.count() }} URL{% if proxies.count() != 1 %}s{% endif %}</small></h3>
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/db/__init__.py", line 2137, in count
    result = raw_query.Count(limit=limit, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/datastore.py", line 1746, in Count
    batch = self.GetBatcher(config=config).next()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/datastore/datastore_query.py", line 3170, in next
    return self.next_batch(self.AT_LEAST_ONE)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/datastore/datastore_query.py", line 3207, in next_batch
    batch = self.__next_batch.get_result()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 613, in get_result
    return self.__get_result_hook(self)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/datastore/datastore_query.py", line 2906, in __query_result_hook
    self._batch_shared.conn.check_rpc_success(rpc)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/datastore/datastore_rpc.py", line 1371, in check_rpc_success
    rpc.check_success()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 579, in check_success
    self.__rpc.CheckSuccess()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_rpc.py", line 134, in CheckSuccess
    raise self.exception
OverQuotaError: The API call datastore_v3.RunQuery() required more quota than is available.
```

**Comment by tom5760** [comment] 2016-10-11 16:42
So the issue is that I'm running on the free tier of Google AppEngine, and am finally (after several years...) coming up against the free quota.  I tried with 89ca7eeb53cdafca014dfb7f1c497fd1574f63cd to use memcache for requests, but that doesn't appear to be working.

I'll take another pass at this soon.  Thanks for the report!

**Comment by tom5760** [comment] 2017-02-24 14:44
For now, I've added billing to my Google App Engine project, so this shouldn't happen anymore (assuming no gigantic spike in traffic!)  Going to close this for now.

**Closed by tom5760** 2017-02-24 14:44 UTC
